modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="kakan"
version="0.1.8"
displayName="KAKAN"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MCreator, Henkyakubi"
description='''
Flower Crowns MOD
'''

[[dependencies.kakan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




